# Задачи
1. Самостоятельно реализовать BoW, TF-IDF
2. Решить задачу классификации с понижением размерности. Использовать самостоятельно реализованные модели из предыдущих ЛР.
3. Решить задачу мягкой кластеризации (ТМ) с помощью LDA

In [1]:
from pathlib import Path
import numpy as np
import os
import sys
sys.path.append(str(Path(os.getcwd()).parent))
from src.ponizenie.PCA import pca
from src.NLP.BoW import BoW
from src.NLP.TFIDF import TFIDF
from src.classification.kNN import KNN
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('../data/NLP/spam.csv', encoding='latin-1')
y = df["v1"]
X = list(df["v2"])

In [14]:
bow = BoW(X)
print(bow.CountVectorized())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
bow.vocabulary()

['!',
 '!!',
 '!!!',
 '!!!!',
 "!!''.",
 '!1',
 '!:-)',
 '!this',
 '#',
 '#150',
 '#5000',
 '$',
 '$1',
 '$140',
 '$180',
 '$2',
 '$350',
 '$5.00',
 '$50',
 '$50...',
 '$700',
 '$900',
 '$95/pax,',
 '%',
 '%.',
 '%of',
 '&',
 '&amp;',
 '&cs',
 '&gt;:(',
 '&it',
 '&lt;#&gt;',
 '&lt;)',
 '&lt;3',
 '&lt;decimal&gt;',
 '&lt;email&gt;',
 '&lt;time&gt;',
 '&lt;url&gt;',
 '&othrs',
 '&sam',
 '&xxx',
 "'",
 "''",
 "''ok'',",
 "'an",
 "'anything'",
 "'comfort'",
 "'doctors'",
 "'heart'...",
 "'help'",
 "'hex'",
 "'hw",
 "'if",
 "'its",
 "'ll",
 "'luxury'",
 "'maangalyam",
 "'married'",
 "'melle",
 "'need'",
 "'rencontre'",
 "'simple'",
 "'taxless'",
 "'terrorist'",
 "'that",
 "'til",
 "'uptown",
 "'wnevr",
 "'xam...",
 '(',
 '($900)',
 '(100p/sms)',
 '(10p/min)',
 '(10p/min).',
 '(150p/sms)',
 '(18',
 '(18+)',
 '(18+).',
 '(20/f)',
 '(25/f)',
 '(25p),',
 '(29/m)',
 '(32/f)',
 '(again),',
 "(alaipayuthe)'",
 '(an',
 '(and',
 '(bank',
 '(book',
 '(but',
 '(career',
 '(come',
 '(flights',
 '(get',

In [3]:
tfidf = TFIDF(X)
tfidf = tfidf.TFIDFvectorize()
print(tfidf)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
nlpdata = pd.DataFrame(tfidf)
nlpdata = pca(nlpdata,n_components = 100)

In [13]:
nlpdata

0      1      2      3      4      5      6      7      8      9      \
0       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
5567    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5568    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5569    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5570    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5571    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      ...  13486    13487  13488  13489  13490  13491  13492  13493  13494  \
0     ...    0.0  0.00000    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1     ...    0.0  0.00000    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2     ...    0.0  0.00000    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3     ...    0.0  0.00000    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4     ...    0.0  0.00000    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...   ...    ...      ...    ...    ...    ...    ...    ...    ...    ...   
5567  ...    0.0  0.00000    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5568  ...    0.0  0.51995    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5569  ...    0.0  0.00000    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5570  ...    0.0  0.00000    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5571  ...    0.0  0.00000    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      13495  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
...     ...  
5567    0.0  
5568    0.0  
5569    0.0  
5570    0.0  
5571    0.0  

[5572 rows x 13496 columns]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(nlpdata, y, test_size=0.15, random_state=4)
knn = KNN(4)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)


In [6]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       704
        spam       0.98      0.80      0.88       132

    accuracy                           0.97       836
   macro avg       0.97      0.90      0.93       836
weighted avg       0.97      0.97      0.96       836



In [7]:
from time import time
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
n_samples = 2000
n_features = 1000
n_topics = 10
n_top_words = 20

In [12]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic #%d:" % topic_idx)
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-n_top_words - 1:-1]]))

In [9]:
df = pd.read_csv('../data/NLP/spam.csv', encoding='latin-1')
y = df["v1"]
X = list(df["v2"])

In [10]:
tf_vectorizer = CountVectorizer(max_df=0.95, min_df=2,
                                max_features=n_features,
                                stop_words='english')
tf = tf_vectorizer.fit_transform(X)

In [11]:
lda = LatentDirichletAllocation(n_components=n_topics, max_iter=20, 
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0).fit(tf)

In [13]:
print_top_words(lda, tf_vectorizer.get_feature_names_out(), 10)

Topic #0:
just ask hey meet min house live end month ah
Topic #1:
prize claim won number cash urgent win txt guaranteed cool
Topic #2:
ok good did way doing night today oh home just
Topic #3:
come ur da ì_ send msg service customer care soon
Topic #4:
day going great said went happy wish hope man lunch
Topic #5:
gt lt know don time want just need think dont
Topic #6:
lor got like wat say pls lol buy cos dun
Topic #7:
free stop reply text txt new www mobile com week
Topic #8:
sorry later love ll dear amp ur life thanks gud
Topic #9:
hi home im babe love phone miss tell mobile text
